=== 666TeamAAA/WAKlab07/data/timetable.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT timetable (days, period+, courses?)>

<!ELEMENT days (day+)>
<!ELEMENT day (booking)>
<!ATTLIST day
    type (mon|tues|wed|thu|fri) #REQUIRED>


<!ELEMENT courses (course+)>
<!ELEMENT course (booking)>


<!ELEMENT period (timeslot)>
<!ELEMENT timeslot (booking)>
<!ELEMENT booking (time, room, instructor)>

<!ELEMENT room (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT instructor (name)>
<!ELEMENT name (#PCDATA)>

=== 666TeamAAA/WAKlab07/data/schedule3.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE timetable SYSTEM 'timetable.dtd'>
<timetable>
    <year>2016</year>
    <term>Winter</term>
    <set>4S</set>
    <program>CST</program>
    <days>
        <day type="mon">
            <booking>
                <time>9:30-10:20</time>
                <room>SW5-1840</room>
                <instructor>
                    <name>Catherine Ryan</name>
                </instructor>
            </booking>
        </day>

        <day type="tues">
            <booking>
                <time>10:30-12:20</time>
                <room>SE12-308</room>
                <instructor>
                    <name>Medhat Elmasry</name>
                </instructor>
            </booking>
        </day>

        <day type="wed">
            <booking>
                <time>12:30-1:20</time>
                <room>SW3-1750</room>
                <instructor>
                    <name>Brenda Fine</name>
                </instructor>
            </booking>
        </day>

        <day type="mon">
            <booking>
                <time>12:30-11:20</time>
                <room>SE12-308</room>
                <instructor>
                    <name>Medhat Elmasry</name>
                </instructor>
            </booking>
        </day>
    </days>

    <period>
        <timeslot>
            <booking>
                <time>9:30-10:20</time>
                <room>SW5-1840</room>
                <instructor>
                    <name>Catherine Ryan</name>
                </instructor>
            </booking>
        </timeslot>
    </period>

    <period>
        <timeslot>
            <booking>
                <time>10:30-12:20</time>
                <room>SE12-308</room>
                <instructor>
                    <name>Medhat Elmasry</name>
                </instructor>
            </booking>
        </timeslot>
    </period>

    <period>
        <timeslot>
            <booking>
                <time>12:30-1:20</time>
                <room>SW3-1750</room>
                <instructor>
                    <name>Brenda Fine</name>
                </instructor>
            </booking>
        </timeslot>
    </period>

    <period>
        <timeslot>
            <booking>
                <time>10:30-11:20</time>
            <room>SE12-308</room>
            <instructor>
                <name>Medhat Elmasry</name>
            </instructor>
        </booking>
    </timeslot>
</period>

<courses>
<course>
    <booking>
        <time>8:30-10:20</time>
        <room>SW5-1840</room>
        <instructor>
            <name>Catherine Ryan</name>
        </instructor>
    </booking>
</course>
<course>
    <booking>
        <time>10:30-12:20</time>
        <room>SE12-308</room>
        <instructor>
            <name>Medhat Elmasry</name>
        </instructor>
    </booking>
</course>
<course>
    <booking>
        <time>12:30-1:20</time>
        <room>SW3-1750</room>
        <instructor>
            <name>Brenda Fine</name>
        </instructor>
    </booking>
</course>
<course>
    <booking>
        <time>12:30-11:20</time>
        <room>SE12-308</room>
        <instructor>
            <name>Medhat Elmasry</name>
        </instructor>
            </booking>
        </course>
    </courses>


</timetable>

=== 666TeamAAA/WAKlab07/data/schedule1.xml
<?xml version="1.0" encoding="UTF-8" ?>
        
<!DOCTYPE timetable SYSTEM 'timetable.dtd'>
<timetable>
    <year>2016</year>
    <term>Winter</term>
    <set>4S</set>
    <program>CST</program>
    <!-- days -->
    <days>
        <day type="Monday">
            <booking period="9:30-11:30" course="BLAW3600">
                <instructor>Catherine Ryan</instructor>
            </booking>
            <booking period="11:30-12:30" course="COMP4735">
                <instructor>Mirela Gutica</instructor>
            </booking>
            <booking period="12:30-14:30" course="COMP4735">
                <instructor>Mirela Gutica</instructor>
            </booking>
        </day>
    </days>

    <!-- periods -->
    <periods>
        <period type="11:30-12:30">
            <booking day="Monday" course="COMP4735">
                <instructor>Mirela Gutica</instructor>
            </booking>
            <booking day="Tuesday" course="COMP4560">
                <instructor>Brenda Fine</instructor>
            </booking>
            <booking day="Thursday" course="COMP4735">
                <instructor>Mirela Gutica</instructor>
            </booking>
        </period>
    </periods>
    <!-- courses-->
    <courses>
        <course type="BLAW3600">
            <booking day="Monday" period="8:30-9:30">
                <instructor>Catherine Ryan</instructor>
            </booking>
            <booking day="Friday" period="8:30-10:30">
                <instructor>Catherine Ryan</instructor>
            </booking>
        </course>
    </courses>
</timetable>
